# Generated by Django 3.0.4 on 2020-03-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundclip',
            name='duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='soundclip',
            name='plays',
            field=models.BigIntegerField(),
        ),
    ]
