# Generated by Django 3.0.4 on 2020-03-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0002_auto_20200329_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
