# Generated by Django 3.0.4 on 2020-04-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0004_guild'),
        ('manage_users', '0004_auto_20200405_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guild',
        ),
        migrations.AlterField(
            model_name='profile',
            name='guilds',
            field=models.ManyToManyField(to='discord_bot.Guild'),
        ),
    ]
