# Generated by Django 3.0.4 on 2020-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discord_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('sound_clips', models.ManyToManyField(to='discord_bot.SoundClip')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
